/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Markus-Schwer/eventing-amqp/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAmqpSources implements AmqpSourceInterface
type FakeAmqpSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var amqpsourcesResource = schema.GroupVersionResource{Group: "sources.knative.dev", Version: "v1alpha1", Resource: "amqpsources"}

var amqpsourcesKind = schema.GroupVersionKind{Group: "sources.knative.dev", Version: "v1alpha1", Kind: "AmqpSource"}

// Get takes name of the amqpSource, and returns the corresponding amqpSource object, and an error if there is any.
func (c *FakeAmqpSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AmqpSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(amqpsourcesResource, c.ns, name), &v1alpha1.AmqpSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmqpSource), err
}

// List takes label and field selectors, and returns the list of AmqpSources that match those selectors.
func (c *FakeAmqpSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AmqpSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(amqpsourcesResource, amqpsourcesKind, c.ns, opts), &v1alpha1.AmqpSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AmqpSourceList{ListMeta: obj.(*v1alpha1.AmqpSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.AmqpSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested amqpSources.
func (c *FakeAmqpSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(amqpsourcesResource, c.ns, opts))

}

// Create takes the representation of a amqpSource and creates it.  Returns the server's representation of the amqpSource, and an error, if there is any.
func (c *FakeAmqpSources) Create(ctx context.Context, amqpSource *v1alpha1.AmqpSource, opts v1.CreateOptions) (result *v1alpha1.AmqpSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(amqpsourcesResource, c.ns, amqpSource), &v1alpha1.AmqpSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmqpSource), err
}

// Update takes the representation of a amqpSource and updates it. Returns the server's representation of the amqpSource, and an error, if there is any.
func (c *FakeAmqpSources) Update(ctx context.Context, amqpSource *v1alpha1.AmqpSource, opts v1.UpdateOptions) (result *v1alpha1.AmqpSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(amqpsourcesResource, c.ns, amqpSource), &v1alpha1.AmqpSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmqpSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAmqpSources) UpdateStatus(ctx context.Context, amqpSource *v1alpha1.AmqpSource, opts v1.UpdateOptions) (*v1alpha1.AmqpSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(amqpsourcesResource, "status", c.ns, amqpSource), &v1alpha1.AmqpSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmqpSource), err
}

// Delete takes name of the amqpSource and deletes it. Returns an error if one occurs.
func (c *FakeAmqpSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(amqpsourcesResource, c.ns, name), &v1alpha1.AmqpSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAmqpSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(amqpsourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AmqpSourceList{})
	return err
}

// Patch applies the patch and returns the patched amqpSource.
func (c *FakeAmqpSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AmqpSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(amqpsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AmqpSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AmqpSource), err
}
