apiVersion: sources.knative.dev/v1alpha1
kind: AmqpSource
metadata:
  name: amqp-source
spec:
  broker: artemis:5672
  topic: test
  user:
    secretKeyRef:
      name: artemis-admin-secret
      key: AMQP_USER
  password:
    secretKeyRef:
      name: artemis-admin-secret
      key: AMQP_PASSWORD

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
---
apiVersion: v1
kind: Secret
metadata:
  name: artemis-admin-secret
type: Opaque
stringData:
  AMQP_USER: "artemis"
  AMQP_PASSWORD: "artemis"
