apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    amqp.eventing.knative.dev/release: devel
    eventing.knative.dev/source: "true"
    duck.knative.dev/source: "true"
    knative.dev/crd-install: "true"
  annotations:
    registry.knative.dev/eventTypes: |
      [
        { "type": "dev.knative.amqp.event" }
      ]
  name: amqpsources.sources.knative.dev
spec:
  group: sources.knative.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        # Workaround, existing schema is incomplete and fails validation.
        x-kubernetes-preserve-unknown-fields: true
  names:
    categories:
      - all
      - knative
      - eventing
      - sources
      - importers
    kind: AmqpSource
    plural: amqpsources
  scope: Namespaced