apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventing-sources-amqp-controller
  labels:
    amqp.eventing.knative.dev/release: devel
rules:

  - apiGroups:
      - sources.knative.dev
    resources:
      - amqpsources
      - amqpsources/finalizers
    verbs: &everything
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - sources.knative.dev
    resources:
      - amqpsources/status
    verbs:
      - get
      - update
      - patch

  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: *everything

  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - secrets
    verbs: *everything

  # For leader election
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs: *everything

---
# The role is needed for the aggregated role source-observer in knative-eventing to provide readonly access to "Sources".
# See https://github.com/knative/eventing/blob/master/config/200-source-observer-clusterrole.yaml.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventing-contrib-amqp-source-observer
  labels:
    eventing.knative.dev/release: devel
    duck.knative.dev/source: "true"
rules:
  - apiGroups:
      - "sources.knative.dev"
    resources:
      - "amqpsources"
    verbs:
      - get
      - list
      - watch