apiVersion: v1
kind: ServiceAccount
metadata:
  name: amqp-controller-manager
  namespace: playground
  labels:
    amqp.eventing.knative.dev/release: devel
secrets:
  - name: amqp-source-key
---
apiVersion: v1
kind: Secret
metadata:
  name: amqp-source-key
  namespace: playground
type: Opaque
data:
  'key.json': ""