apiVersion: v1
kind: ServiceAccount
metadata:
  name: amqp-webhook
  namespace: playground
  labels:
    amqp.eventing.knative.dev/release: devel

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amqp-webhook
  labels:
    amqp.eventing.knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: amqp-webhook
    namespace: playground
roleRef:
  kind: ClusterRole
  name: amqp-webhook
  apiGroup: rbac.authorization.k8s.io